apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment # Name of the deployment 
  labels:
    app: go-webapp  # label for the deployment 
spec:
  replicas: 2  # No of desired pod
  selector:
    matchLabels:
      app: go-webapp # selectors to find pods managed by this deployment 
  template:
    metadata:
      labels:
        app: go-webapp # Lables apply to the pods created by this deployment 
    spec:
      containers:
        - name: go-webapp-container
          image: senthilnd/go-sen-web-app2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
